Add optional `encoding` argument to set output character encoding
abrom/henkei pull request #47
Opened 2024-06-07 05:46 UTC by SimonBrazell

#### What's this PR do?
Adds an optional `encoding` argument to `#text`, `#html` and `.read` for setting the output character encoding, which is passed to Tika as the `--encoding` option. This value is validated against Ruby's `Encoding.name_list`, raising an `ArgumentError` if it isn't included in the list.

#### Why is it needed?
So we can set the output encoding via Henkei / Tika instead of having to do it ourselves afterwards. 

#### Where should the reviewer start?

- `lib/henkei.rb:222`

#### How should this be manually tested?

```ruby
henkei = Henkei.new 'sample.pages'
utf_8_text = henkei.text(encoding: 'UTF-8')
utf_8_text.encoding 
=> #<Encoding:UTF-8>
```

2024-06-10 06:32 UTC, abrom requested changes

2024-06-10 06:32 UTC, abrom commented on lib/henkei.rb
> +      stdin.puts data
`capture2` uses `write` at this stage. It is also wrapped in a begin/rescue block catching the `Errno::EPIPE` error.

Looking at the documentation/source they do slightly different things.. including `puts` writing an extra newline

2024-06-10 06:32 UTC, abrom commented on lib/henkei.rb
> +      out_reader = Thread.new { stdout.read }
and it also sets up the read thread before writing  to the input pipe

2024-06-11 00:20 UTC, SimonBrazell commented
@abrom I modified the `Open3.popen2` call to more closely match the `capture2` source.

2024-06-13 23:17 UTC, abrom approved these changes
Nice one @SimonBrazell 👍

2024-06-13 23:21 UTC, merged